SLEEP_TIME_AFTER_LOAD=0.3

# RETRY_INTERVAL is the sleep time between retry attempts. 
RETRY_INTERVAL=1
ELEMENT_LOADING_TIMEOUT=5
# ELEMENT_LOADING_TIMEOUT=2

# The setting of the special border around the selected element.
HIGHLIGHT_ELEMENT_BORDER = 4
HIGHLIGHT_ELEMENT_COLOR = "red"
HIGHLIGHT_ELEMENT_DURATION = 1
